
datasets:
  train_batch_size: 3
  val_batch_size: 4
  test_batch_size: 4
  num_workers: 16
  download:
    data:
      filename: BingRGB.zip
      url: https://drive.google.com/file/d/1VTcCWjm-neMdLuTN96cVKGO7BravpVLt/view?usp=sharing
      extract_to: ./data/BingRGB/
    weight:
      filename: pytorch-weight.zip
      url: https://drive.google.com/file/d/1TGnQ67ZazG4B8fRsW8m313CylQ57Bl0F/view?usp=share_link
      extract_to: ./data/pytorch-weight/
  train_sup_data_path: ./data/BingRGB/train_sup
  train_unsup_data_path: ./data/BingRGB/train_unsup
  val_data_path: ./data/BingRGB/val
  test_data_path: ./data/BingRGB/val
  transforms:
    train:
      - ToTensor
    val:
      - ToTensor
    test:
      - ToTensor
trainer:
  train:
    devices: -1
    num_nodes: 1
    accelerator: cuda
    strategy: ddp
    max_epochs: 100
    sync_batchnorm: True
    num_sanity_val_steps: 0
    # fast_dev_run: 10
    # limit_train_batches: 10
    # limit_val_batches: 10
    log_every_n_steps: 10
  logger:
    TensorBoardLogger:
      save_dir: logs/
      name: tb_cps
    CSVLogger:
      save_dir: logs/
      name: csv_cps
    WandbLogger:
      project: "8th_cps"
      save_dir: logs/
      name: slow_lightspeed
  callbacks:
    ModelCheckpoint: 
      monitor: miou
      dirpath: ./checkpoints
      filename: last-best-{epoch:02d}-{miou:.2f}
      save_top_k: 5
      mode: max
      save_last: True
      verbose: True
      # save_on_train_epoch_end: True
      # every_n_epochs: 0
  test:
    devices: 1
    num_nodes: 1
    accelerator: cuda