
datasets:
  batch_size: 2
  download:
    raw:
      filename: BingRGB_raw.zip
      source: https://iubedubd-my.sharepoint.com/:u:/g/personal/1731117_iub_edu_bd/EfHtUykBqFBDlBgTG9Noz5cBmv1tcWK7g52NSMdsgenhDQ?e=2q3yrB
      extract_to: ./data/BingRGB/
    data:
      filename: BingRGB.zip
      source: https://iubedubd-my.sharepoint.com/:u:/g/personal/1731117_iub_edu_bd/EUFzz7hu3gZHqaTDuHm791IB440iHaTfWFhxVpbcfZTmlg?e=UTy7mM
      extract_to: ./data/BingRGB/
    weight:
      filename: pytorch-weight.zip
      source: https://iubedubd-my.sharepoint.com/:u:/g/personal/1731117_iub_edu_bd/ESLri6VtHrpMs6xLDC6zrdwBFNumLgR9--2KNUlJBfHDkQ?e=rrwIls
      extract_to: ./data/
  train_data_path: ./data/BingRGB/train
  val_data_path: ./data/BingRGB/val
  test_data_path: ./data/BingRGB/test
  transforms:
    train:
      - ToTensor
    val:
      - ToTensor
    test:
      - ToTensor
trainer:
  train:
    devices: -1
    num_nodes: 1
    accelerator: cuda
    # strategy: ddp
    max_epochs: 40
    fast_dev_run: 1
    # limit_train_batches: 50
    # limit_val_batches: 20
    log_every_n_steps: 10
  logger:
    TensorBoardLogger:
      save_dir: logs/
      name: tb_cps
    CSVLogger:
      save_dir: logs/
      name: csv_cps
    WandbLogger:
      project: "wb_cps"
      save_dir: logs/
  callbacks:
    ModelCheckpoint: 
      monitor: cps_loss
      dirpath: ./checkpoints
      filename: model-{epoch:02d}-{cps_loss:.2f}
      save_top_k: 3
      mode: min
      save_last: True
  test:
    devices: -1
    num_nodes: 1
    accelerator: cuda
    strategy: ddp
    log_every_n_steps: 10